/*
 * This source file was generated by the Gradle 'init' task
 */
package shuntingyard;

public class App {

    public static void main(String[] args) {
        Expression output = new Expression("2*3^6");
        System.out.println(output.convertToPostfix());
        System.out.println(output);
    }
}
