/*
 * This source file was generated by the Gradle 'init' task
 */
package shuntingyard;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Expression output;

        if(args.length != 0){
            for(int i = 0; i < args.length; i++){
                output = new Expression(args[i]);
                System.out.println(output.convertToPostfix());
            }
            return;
        }
        
        Scanner scannie = new Scanner(System.in);
        String input = "-1";
        System.out.println("Type an expression to be converted to postfix");
        input = scannie.next();
        
        while(!input.equals("Q")){
            System.out.println("|" + input + "|");
            output = new Expression(input);
            try {
                System.out.println(output.convertToPostfix());
            } catch (Exception e) {
                System.out.println("Please match parenthesis and don't use any uninterpretable symbols");
            }
            System.out.println("\nType another expression, or \"Q\" to exit.");
            input = scannie.next();
        }
        
        scannie.close();
    }
}
